### PR TITLE
update version setup.py

### PR DESCRIPTION
**Pull request by edelfour**
test pull request

### CODE REVIEW

**Comment by jktjkt** [comment]
Can you please resubmit this against the `master` branch? It's an error which affects both `develop` and `master`, and therefore I would like to have it fixed in the more-stable branch as well.

(I tried doing this via GitHub UI, and it won't rebase, unfortunately. I'll also leave that pull request open for Esther to merge.)

**Comment by EstherLerouzic** [comment]
I still do not have the "merge" button ...

**Comment by jktjkt** [comment]
> I still do not have the "merge" button ...

@EstherLerouzic , can you check now? I changed the ACL at the repo level from "write" to "maintain", hope this helps.

**Comment by edelfour** [comment]
Hello @jktjkt,
Switch to master done.

**Comment by EstherLerouzic** [comment]
@jktjkt : when I approve I have the green button ! Tell me if you want me to merge  or to delete ! (this pr was only to test !

**Comment by jktjkt** [comment]
I think that the actual change made in commit be14622ffb734a5441f798377950cfb08f36c0d4 is good (thanks for catching that error, @edelfour). Its git parent commit is rather old 978a9407fa7ee545c068350a63efd0b2ca836095. I see that this is what is currently in the `master` branch of the `Orange-OpenSource/gnpy` fork, which is probably why @edelfour based this PR on that.

I think that a best steps now are to:
- in a local checkout, switch to an up-to-date clone of this repo based on the current `master`, i.e., commit 9a0eece
- `git cherry-pick be14622ffb734a5441f798377950cfb08f36c0d4` on top of that,
- push that thing into `Orange-OpenSource/gnpy`'s `pr_test` branch

Then this PR can be merged.

**Pull request merged**
