### PR TITLE
Service aggregation clean

### PR DESCRIPTION
**Pull request by EstherLerouzic**
For you to see my work on
- aggregation feature
- automatic mode selection feature
- cost feature
+ various small fixes

Esther

### CODE REVIEW

**Comment by EstherLerouzic** [comment]
This PR also corrects #150 and #149

**Comment by dutc** [comment]
Is this ready for review?

**Comment by EstherLerouzic** [comment]
The feature is ready . Should I  first rebase my work on current develop and do the merging ?

**Comment by ojnas** [comment]
This PR introduces a new EDFA "type_def": "openroadm". Is this meant to model an amplifier meeting the Open ROADM MSA specification (http://www.openroadm.org/download.html)? I'm curious about how the following noise figure model has been derived:

`nf_avg = polyval(self.params.nf_model.nf_coef, pin_ch)`
with `nf_coef` specified in `eqpt_config.json`.

It does not seem to be consistent with the noise mask (Incremental OSNR vs. Preceding Span Loss) specified in the Open ROADM MSA but maybe I misunderstand something.

**Comment by jeanluc-auge** [comment]
> This PR introduces a new EDFA "type_def": "openroadm". Is this meant to model an amplifier meeting the Open ROADM MSA specification (http://www.openroadm.org/download.html)? I'm curious about how the following noise figure model has been derived:
> 
> `nf_avg = polyval(self.params.nf_model.nf_coef, pin_ch)`
> with `nf_coef` specified in `eqpt_config.json`.
> 
> It does not seem to be consistent with the noise mask (Incremental OSNR vs. Preceding Span Loss) specified in the Open ROADM MSA but maybe I misunderstand something.

it is consistent, but with the new MSA spec, not with the older one ;)
=> I'm coordinating the openroadm amplifier group and we just approved a revision of the standard ILA spec, and the definition of a new low noise ILA for long distance application.
=> I am currently updating and finlaizing the MSA spec. But I don't know when it will be online

**Comment by dutc** [comment]
Superseded by #168

**Pull request closed without merging**
