### PR TITLE
docker files

### PR DESCRIPTION
**Pull request by jeanluc-auge**
see README.md and issue #260

### CODE REVIEW

**Comment by ojnas** [comment]
I tested it on Docker for Windows and it works as described, nice!

Having a shared folder is convenient but it would be even more convenient if the examples folder could be shared so that existing input files, etc., could be edited directly from the host. Alternatively add some description in the README how to copy files from the example folder to the shared folder and work from there.

**Comment by ojnas** [comment]
Here is an alternative approach that shares the example folder. This doesn't use docker-compose but I think the same approach could be used for that case.

1. Download this [Dockerfile](https://github.com/ojnas/oopt-gnpy/blob/docker/docker/Dockerfile).
2. Change to the directory with the downloaded Dockerfile.
3. Build the docker image with:
`docker build -t gnpy .`
4. Run the docker container with one of the following commands depending on platform:
For Windows using PowerShell:
`docker run -it --rm -v ${PWD}:/oopt-gnpy-develop/shared/ gnpy`
For Linux (and I think also Mac):
` docker run -it --rm -v $(pwd):/oopt-gnpy-develop/shared/ gnpy`
5. In the resulting bash prompt, run e.g. `python3 transmission_main_example.py`.

This approach should create an examples folder in the same directory as the Dockerfile. Changes to any file in this folder, e.g. eqpt_config.json, should be seen also in the container and should persist when stopping and restarting the container.

**Comment by jeanluc-auge** [comment]
Thanks Jonas, I pushed a new version

**Comment by jktjkt** [comment]
I'm closing this in favor of #295. Thanks for the code, it helped me get the full automation running!

**Pull request closed without merging**
