### PR TITLE
Api rest

### PR DESCRIPTION
**Pull request by ahmed-triki**
This is an implementation of an API rest for GNPy. The http server is based on flask, so the installation of this package is mandatory. The input/output of the api-rest are modeled by a yang data model.
In addition to the Rest mode, the new code keeps the possibility to use the current CLI (Command Line Interface) mode.
To activate the Rest mode, the user has to launch the following command : 
python path_requests_run.py --rest
The API-rest client has to take into account the following connection parameters: 
- URL: http://<ip_address>:5000/gnpy/api/v1.0/files 
- authentication: username: gnpy/ password: gnpy
- Rest-Method: POST / The body of the request is composed of the topology and the service data in json format.
This pull-request has to be merged after #215 .
Todo: add explanation of the body and the response models of the API-REST.

### CODE REVIEW

**Comment by ahmed-triki** [comment]
Thank you @ojnas  for your interest to the code.
Exactly, the actual yang files are not used directly by the code, they are only included as a reference. However, the Post request has to be compliant with the yang model in order to be understandable by GNPy code. I have already used these yang models in T-PCE in order to enable T-PCE to interrogate GNPy and check the feasibility of the computed path.

**Comment by ojnas** [comment]
Maybe this REST API functionality should be part of the gnpy core library, i.e. placed in a module in the gnpy/core folder and not just as a part of the `path_requests_run.py` example script as it is now?

**Comment by dutc** [comment]
@ojnas I agree that the REST functionalit should be extracted from `path_requests_run.py` and we have discussed putting it into a separate library from http://github.com/telecominfraproject/oopt-gnpy

We discussed creating a repo like http://github.com/telecominfraproject/oopt-interfaces or some such to collect higher-level "interfaces" for `gnpy`, but we're still discussing if this is the right name. The reason to split this off into its own repo are:
- allows the REST API to target a specific version of the core, underlying library
- allows contributors to the core, underlying library (who may have no background in Flask/REST APIs) to make changes without worrying about breaking REST API
- keeps the dependency footprint of the core library small (since Flask may not be an approved or preferred tool within all organizations)

**Comment by dutc** [comment]
Hi, @ahmed-triki, as per our call on Thursday, I have created http://github.com/telecominfraproject/oopt-tools for "tool"-level code for OOPT. This would allow us to organize ourselves as follows:
- github.com/telecominfraproject/oopt-raman: scientific-level code
- github.com/telecomifnraproject/oopt-gnpy: core library code
- github.com/telecominfraproject/oopt-tools: user-facing tools code (REST API, command-line tools, etc.)

**Comment by EstherLerouzic** [comment]
please refer to the new PR #309   for this work

**Comment by jktjkt** [comment]
We have [decided to remove the `develop` branch](https://telecominfraproject.workplace.com/groups/OOPT.PSE/permalink/1735137103317818/), and as a result of doing that, this PR got auto-closed on GitHub. If you believe that this change is still relevant and that it was closed by accident, please [submit your patch to our Gerrit](https://review.gerrithub.io/Documentation/user-upload.html), or just comment here and I'll help sort this out.

**Pull request closed without merging**
