### PR TITLE
docs: Show a pretty picture of GNPy in action

### PR DESCRIPTION
**Pull request by jktjkt**
Here's how the [landing page of the repository at GitHub will look if this is merged](https://github.com/jktjkt/oopt-gnpy/tree/docs).

### CODE REVIEW

**Comment by jktjkt** [comment]
> Nice banner ! do you think you could add the screen shot of a simulation as well ?

How do you like this one?

[asciicast](https://asciinema.org/a/H1WJjUnObzIPwje6MJnofDJDX)

**Comment by jktjkt** [comment]
A note to the future maintainer: there were some issues with hosting the resulting screencast "just on github" with no dependency on external services that might go away (hi rawgithub.com). In the end, the way to go was using the `gh-pages` branch which apparently [supports unfiltered SVG content](https://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown). The actual animated data therefore live in another branch than this one.

**Comment by EstherLerouzic** [comment]
Looks nice ! thanks

**Comment by jktjkt** [comment]
> Suggest to add 1-2 sentences in front of the example to give an idea what's going on and set expectation. Perhaps something alike:
> This example demonstrates how GNPy can be used to check the expected SNR at the end of the line by varying the channel input power.

Added, thanks.

**Pull request merged**
