### PR TITLE
Explicitly set all nodes in CORONET example to ROADM

### PR DESCRIPTION
**Pull request by ojnas**
See #130

Also updated README to reflect that by default propagation is now between Abilene and Albany again.

Will propose a separate PR to avoid crashing because source and destination are the same.

### CODE REVIEW

**Comment by dutc** [comment]
References #130 

Since the Coronet files are generated from the original .XLS, we may want to fix the converter.

Otherwise, we risk these changes being accidentally reverted in future work.

Also, could you separate commit 48198bd from this PR?

**Comment by dutc** [comment]
My mistake. I saw the change to the .json but I didn't see the change to the .xls. You did the right thing.

Don't worry about separating your commits for this PR. I'll handle it on my end.

**Comment by ojnas** [comment]
Ok, thanks, but I would still like to understand how to separate commits. I wanted to do it but gave up after fighting with git for too long...

**Comment by dutc** [comment]
We've previously discussed doing a `git` warmup call for the code contributors to cover some of these types of issues. If you'd be interested, I'll reraise this as something we might want to do.

In the meantime, check out: https://github.com/k88hudson/git-flight-rules

**Comment by dutc** [comment]
We've previously discussed doing a `git` warmup call for the code contributors to cover some of these types of issues. If you'd be interested, I'll reraise this as something we might want to do.

In the meantime, check out: https://github.com/k88hudson/git-flight-rules

**Pull request merged**
