### PR TITLE
Update README.rst

### LINKED ISSUE #127: Wrong or outdated information in README about CORONET
The following text is wrong:

> You can specify a different network at the command line as follows. For example, to use the CORONET Continental US (CONUS) network defined in examples/coronet_conus_example.json:

```
$ cd examples
$ python transmission_main_example.py CORONET_Global_Topology.json
```

Notice the different json filenames. The file coronet_conus_example.json does not exist. Further down there is this text:

> The main transmission example will calculate the average signal OSNR and SNR across 93 network elements (transceiver, ROADMs, fibers, and amplifiers) between two transceivers selected by the user. (By default, for the CORONET US network, it will show the transmission of spectral information between Abilene, Texas and Albany, New York.)

When the script is run with CORONET_Global_Topology.json as specified the propagation is between Albuquerque and Atlanta (not between Abilene and Albany).

### PR DESCRIPTION
**Pull request by ojnas**
Some fixes to the README:

- Tried to fix #127 (also removed reference to 93 network elements since I don't think it was correct).

- Removed some text about amplifier setting in relation to transmission_main_example.py since this script does not use advanced EDFA model by default.

- Other minor fixes.

### CODE REVIEW

**Comment by MiquelGA** [comment]
Few minor issues regarding the README are still to be addressed (aslo considering #127 ):
- examples/coronet_conus_example.json does not exist. Indeed, this can be verified just by clicking the link in the README.
- As commented by @ojnas , "When the script is run with CORONET_Global_Topology.json as specified the propagation is between Albuquerque and Atlanta (not between Abilene and Albany)." I think this path traverses 33 elements and not 93.
- Typo "This file defines the equipEment libraIries"

**Comment by ojnas** [comment]
Hi @MiquelGA 

You should look at the develop branch where I think the CORONET issues have been fixed. (As an aside I think it may make sense to set develop as the default branch on github but I think this has been discussed before.)

As for the typo, submit a PR.

**Comment by MiquelGA** [comment]
Hi @ojnas , thanks for the reply!
I will submit a PR of the minor issues.

**Comment by ojnas** [comment]
You have to fork the repository and submit the PR from your fork:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Pull request merged**
